---
org: experimentstryingtolearn

app: test1

service: test1

configValidationMode: error

provider:
  name: aws
  architecture: arm64
  memorySize: 128
  timeout: 10
  deploymentMethod: direct
  runtime: provided.al2023
  stage: ${opt:stage, 'dev'}
  region: eu-north-1

package:
  individually: true

plugins:
  - serverless-go-plugin

functions:
  proxy:
    handler: proxy/main.go
    events:
      - httpApi:
          method: any
          path: /{proxy+}

custom:
  go:
    supportedRuntimes: ["provided.al2023"]
    buildProvidedRuntimeAsBootstrap: true
